function Hd = filtro
%FILTRO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 12-Jul-2018 17:37:51

Numerator   = [0.028 0.053 0.071 0.053 0.028];  % Numerator coefficient
% vector
Denominator = [1 -2.026 2.148 -1.159 0.279];    % Denominator coefficient
% vector

Hd = dsp.IIRFilter( ...
    'Numerator', Numerator, ...
    'Denominator', Denominator);

% [EOF]
